language: php

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

php:
  - 7.4

env:
  global:
  - MOODLE_BRANCH=MOODLE_39_STABLE
  matrix:
  - DB=pgsql

before_install:
- phpenv config-rm xdebug.ini
- pwd
- cd ../..
- composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- pwd
- moodle-plugin-ci install --no-init
- find . -name '.env'
- cat ./ci/.env
- export

script:
- pwd
- moodle-plugin-ci phplint
- pwd
- ls -Al moodle
- ls -Al moodle/node_modules
- ls -Al moodle/node_modules/.bin
- moodle-plugin-ci mustache
- pwd
- find . -name '.env'
- cat ./ci/.env
- export
